# Generated by Django 2.1.4 on 2018-12-30 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uptime', models.DateTimeField(blank=True, null=True)),
                ('downtime', models.DateTimeField(blank=True, null=True)),
                ('downtime_counter', models.IntegerField()),
                ('status', models.IntegerField()),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
