# Generated by Django 2.1.4 on 2018-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='downtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='downtime_counter',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='uptime',
            field=models.DateTimeField(null=True),
        ),
    ]
